import globals from 'globals';

import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';

// import react from 'eslint-plugin-react';
// import reactHooks from 'eslint-plugin-react-hooks';

import eslintReact from '@eslint-react/eslint-plugin';
import { reactRefresh } from 'eslint-plugin-react-refresh';
// eslint-disable-next-line id-match/imports-match
import jsxA11y from 'eslint-plugin-jsx-a11y';
import eslintConfigPrettier from 'eslint-config-prettier/flat';

import idMatch from 'eslint-plugin-id-match';

export default defineConfig([
  { ignores: ['dist/**', '.next/**', 'next-env.d.ts'] },

  {
    files: ['**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    languageOptions: { parser: tseslint.parser },
  },
  {
    files: ['src/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    languageOptions: { parserOptions: { projectService: true } },
  },

  {
    files: ['**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    plugins: { '@typescript-eslint': tseslint.plugin },
    rules: {
      'array-callback-return': 'error',
      'constructor-super': 'error',
      'for-direction': 'warn',
      'getter-return': 'error',
      'no-async-promise-executor': 'warn',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['warn', 'always'],
      'no-const-assign': 'error',
      'no-constant-binary-expression': ['warn', { checkRelationalComparisons: true }],
      'no-constant-condition': 'warn',
      'no-constructor-return': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      '@typescript-eslint/no-dupe-class-members': 'error',
      'no-dupe-else-if': 'warn',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'warn',
      'no-duplicate-imports': 'warn',
      'no-empty-character-class': 'warn',
      'no-empty-pattern': 'warn',
      'no-ex-assign': 'error',
      'no-fallthrough': 'warn',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': ['error', 'both', { blockScopedFunctions: 'disallow' }],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': [
        'error',
        {
          skipComments: false,
          skipJSXText: false,
        },
      ],
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'error',
      'no-prototype-builtins': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'warn',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'warn',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'warn',
      'no-unsafe-optional-chaining': 'error',
      '@typescript-eslint/no-unused-private-class-members': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          varsIgnorePattern: '^_',
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          reportUsedIgnorePattern: true,
        },
      ],
      '@typescript-eslint/no-use-before-define': ['error', { ignoreTypeReferences: false }],
      'no-useless-assignment': 'warn',
      'no-useless-backreference': 'error',
      'require-atomic-updates': 'warn',
      'use-isnan': [
        'error',
        {
          enforceForSwitchCase: true,
          enforceForIndexOf: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: true,
        },
      ],

      'arrow-body-style': ['error', 'as-needed'],
      'block-scoped-var': 'error',
      '@typescript-eslint/class-methods-use-this': [
        'warn',
        {
          enforceForClassFields: false,
          ignoreOverrideMethods: true,
          ignoreClassesThatImplementAnInterface: true,
        },
      ],
      curly: ['error', 'all'],
      'default-case': 'warn',
      'default-case-last': 'warn',
      eqeqeq: ['error', 'always'],
      'func-name-matching': [
        'error',
        {
          considerPropertyDescriptor: true,
          includeCommonJSModuleExports: true,
        },
      ],
      'func-names': 'error',
      'func-style': 'error',
      'grouped-accessor-pairs': ['error', 'anyOrder', { enforceForTSTypes: true }],
      'logical-assignment-operators': ['warn', 'always', { enforceForIfStatements: true }],
      'no-alert': 'error',
      '@typescript-eslint/no-array-constructor': 'warn',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-console': 'error',
      'no-delete-var': 'error',
      'no-else-return': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-empty-static-block': 'warn',
      'no-eq-null': 'error',
      'no-eval': 'warn',
      'no-extend-native': 'warn',
      'no-extra-bind': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-extra-label': 'warn',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': ['error', { lexicalBindings: false }],
      '@typescript-eslint/no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-multi-assign': 'error',
      'no-new': 'warn',
      'no-new-func': 'warn',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-object-constructor': 'error',
      'no-plusplus': 'error',
      'no-proto': 'error',
      '@typescript-eslint/no-redeclare': 'error',
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'warn',
      'no-undefined': 'error',
      'no-unneeded-ternary': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      'no-unused-labels': 'warn',
      'no-useless-call': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      '@typescript-eslint/no-useless-constructor': 'warn',
      'no-useless-escape': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-var': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'object-shorthand': 'warn',
      'one-var': ['error', 'never'],
      'operator-assignment': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      'prefer-exponentiation-operator': 'warn',
      'prefer-numeric-literals': 'warn',
      'prefer-object-has-own': 'warn',
      'prefer-object-spread': 'warn',
      'prefer-regex-literals': 'warn',
      'prefer-rest-params': 'error',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'preserve-caught-error': 'warn',
      'require-unicode-regexp': ['error', { requireFlag: 'u' }],
      'require-yield': 'warn',
      strict: 'error',
      'symbol-description': 'warn',
      'vars-on-top': 'error',
      yoda: ['warn', 'never', { exceptRange: true }],

      '@typescript-eslint/adjacent-overload-signatures': 'warn',
      '@typescript-eslint/array-type': ['warn', { default: 'array' }],
      '@typescript-eslint/consistent-generic-constructors': 'warn',
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          objectLiteralTypeAssertions: 'never',
          arrayLiteralTypeAssertions: 'never',
        },
      ],
      '@typescript-eslint/method-signature-style': 'error',
      '@typescript-eslint/no-confusing-non-null-assertion': 'warn',
      '@typescript-eslint/no-duplicate-enum-values': 'warn',
      '@typescript-eslint/no-empty-object-type': [
        'error',
        {
          allowInterfaces: 'always',
          allowObjectTypes: 'always',
        },
      ],
      '@typescript-eslint/no-extra-non-null-assertion': 'warn',
      '@typescript-eslint/no-extraneous-class': 'warn',
      '@typescript-eslint/no-import-type-side-effects': 'warn',
      '@typescript-eslint/no-inferrable-types': 'warn',
      '@typescript-eslint/no-invalid-void-type': 'error',
      '@typescript-eslint/no-misused-new': 'warn',
      '@typescript-eslint/no-namespace': 'error',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      '@typescript-eslint/no-require-imports': 'error',
      '@typescript-eslint/no-this-alias': 'warn',
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'warn',
      '@typescript-eslint/no-unnecessary-type-constraint': 'warn',
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
      '@typescript-eslint/no-unsafe-function-type': 'error',
      '@typescript-eslint/no-useless-empty-export': 'warn',
      '@typescript-eslint/no-wrapper-object-types': 'error',
      '@typescript-eslint/parameter-properties': ['warn', { prefer: 'parameter-property' }],
      '@typescript-eslint/prefer-as-const': 'warn',
      '@typescript-eslint/prefer-for-of': 'warn',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/prefer-literal-enum-member': 'error',
      '@typescript-eslint/prefer-namespace-keyword': 'error',
      '@typescript-eslint/triple-slash-reference': [
        'error',
        {
          lib: 'never',
          types: 'never',
        },
      ],
    },
  },
  {
    files: ['**/*.{js,mjs,cjs,jsx}'],
    rules: {
      'consistent-return': 'error',

      'dot-notation': 'warn',
      'no-implied-eval': 'warn',
      'no-throw-literal': 'error',
      'prefer-destructuring': 'warn',
      'prefer-promise-reject-errors': 'error',
      'require-await': 'warn',
    },
  },
  {
    files: ['src/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    rules: {
      // '@typescript-eslint/consistent-return': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/dot-notation': ['warn', { allowIndexSignaturePropertyAccess: true }],
      '@typescript-eslint/no-implied-eval': 'warn',
      '@typescript-eslint/only-throw-error': ['error', { allowThrowingUnknown: false }],
      '@typescript-eslint/prefer-destructuring': 'warn',
      '@typescript-eslint/prefer-promise-reject-errors': 'error',
      '@typescript-eslint/require-await': 'warn',

      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/consistent-type-exports': ['error', { fixMixedExportsWithInlineTypeSpecifier: true }],
      '@typescript-eslint/no-array-delete': 'error',
      '@typescript-eslint/no-base-to-string': 'error',
      '@typescript-eslint/no-confusing-void-expression': ['error', { ignoreVoidOperator: true }],
      '@typescript-eslint/no-deprecated': 'warn',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-meaningless-void-operator': ['warn', { checkNever: true }],
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/no-misused-spread': 'error',
      '@typescript-eslint/no-redundant-type-constituents': 'warn',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
      '@typescript-eslint/no-unnecessary-condition': [
        'warn',
        {
          allowConstantLoopConditions: 'always',
          checkTypePredicates: true,
        },
      ],
      '@typescript-eslint/no-unnecessary-qualifier': 'warn',
      '@typescript-eslint/no-unnecessary-template-expression': 'warn',
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/no-unnecessary-type-conversion': 'warn',
      // '@typescript-eslint/no-unnecessary-type-parameters': 'error',
      '@typescript-eslint/no-unsafe-enum-comparison': 'error',
      '@typescript-eslint/no-unsafe-unary-minus': 'error',
      '@typescript-eslint/no-useless-default-assignment': 'warn',
      '@typescript-eslint/non-nullable-type-assertion-style': 'warn',
      '@typescript-eslint/prefer-find': 'warn',
      '@typescript-eslint/prefer-includes': 'warn',
      '@typescript-eslint/prefer-nullish-coalescing': 'warn',
      '@typescript-eslint/prefer-readonly': 'warn',
      '@typescript-eslint/prefer-reduce-type-parameter': 'warn',
      '@typescript-eslint/prefer-regexp-exec': 'warn',
      '@typescript-eslint/prefer-return-this-type': 'warn',
      '@typescript-eslint/prefer-string-starts-ends-with': 'warn',
      '@typescript-eslint/related-getter-setter-pairs': 'warn',
      '@typescript-eslint/require-array-sort-compare': 'error',
      '@typescript-eslint/restrict-plus-operands': 'error',
      '@typescript-eslint/return-await': ['error', 'always'],
      '@typescript-eslint/strict-boolean-expressions': 'error',
      '@typescript-eslint/strict-void-return': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': ['warn', { requireDefaultForNonUnion: true }],
      '@typescript-eslint/unbound-method': 'error',
    },
  },

  // {
  //   files: ['src/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
  //   plugins: { react },
  //   rules: {
  //     // 'react/async-server-action': 'warn',
  //     'react/button-has-type': 'warn',
  //     'react/checked-requires-onchange-or-readonly': 'error',
  //     'react/default-props-match-prop-types': ['error', { allowRequiredDefaults: false }],
  //     'react/destructuring-assignment': ['warn', 'always'],
  //     'react/display-name': ['error', { checkContextObjects: true }],
  //     'react/forbid-foreign-prop-types': ['error', { allowInPropTypes: true }],
  //     // 'react/forward-ref-uses-ref': 'warn',
  //     'react/function-component-definition': [
  //       'warn',
  //       {
  //         namedComponents: 'arrow-function',
  //         unnamedComponents: 'arrow-function',
  //       },
  //     ],
  //     'react/iframe-missing-sandbox': 'warn',
  //     'react/jsx-boolean-value': 'warn',
  //     'react/jsx-closing-bracket-location': 'warn',
  //     'react/jsx-closing-tag-location': 'warn',
  //     'react/jsx-curly-brace-presence': ['warn', 'never'],
  //     'react/jsx-curly-newline': 'warn',
  //     'react/jsx-curly-spacing': 'warn',
  //     'react/jsx-equals-spacing': 'warn',
  //     // 'react/jsx-filename-extension': 'error',
  //     'react/jsx-first-prop-new-line': 'warn',
  //     'react/jsx-fragments': ['warn', 'syntax'],
  //     'react/jsx-indent': [
  //       'warn',
  //       2,
  //       {
  //         checkAttributes: true,
  //         indentLogicalExpressions: true,
  //       },
  //     ],
  //     'react/jsx-indent-props': ['warn', 2],
  //     'react/jsx-key': [
  //       'warn',
  //       {
  //         checkFragmentShorthand: true,
  //         checkKeyMustBeforeSpread: true,
  //         warnOnDuplicates: true,
  //         // ignorePrimitives: true,
  //       },
  //     ],
  //     'react/jsx-newline': 'warn',
  //     'react/jsx-no-comment-textnodes': 'warn',
  //     'react/jsx-no-constructed-context-values': 'warn',
  //     'react/jsx-no-duplicate-props': 'error',
  //     'react/jsx-no-leaked-render': 'warn',
  //     'react/jsx-no-script-url': 'warn',
  //     'react/jsx-no-target-blank': [
  //       'warn',
  //       {
  //         warnOnSpreadAttributes: true,
  //         allowReferrer: true,
  //         forms: true,
  //       },
  //     ],
  //     'react/jsx-no-undef': ['error', { allowGlobals: true }],
  //     'react/jsx-no-useless-fragment': ['warn', { allowExpressions: true }],
  //     'react/jsx-one-expression-per-line': ['warn', { allow: 'non-jsx' }],
  //     'react/jsx-pascal-case': 'warn',
  //     'react/jsx-props-no-multi-spaces': 'warn',
  //     'react/jsx-props-no-spread-multi': 'error',
  //     'react/jsx-tag-spacing': ['warn', { beforeClosing: 'proportional-always' }],
  //     'react/jsx-uses-vars': 'warn',
  //     'react/jsx-wrap-multilines': [
  //       'error',
  //       {
  //         declaration: 'parens-new-line',
  //         assignment: 'parens-new-line',
  //         return: 'parens-new-line',
  //         arrow: 'parens-new-line',
  //         condition: 'parens-new-line',
  //         logical: 'parens-new-line',
  //         prop: 'parens-new-line',
  //       },
  //     ],
  //     'react/no-access-state-in-setstate': 'warn',
  //     'react/no-adjacent-inline-elements': 'warn',
  //     'react/no-children-prop': ['warn', { allowFunctions: false }],
  //     'react/no-danger': 'warn',
  //     'react/no-danger-with-children': 'warn',
  //     'react/no-deprecated': 'warn',
  //     'react/no-did-mount-set-state': 'warn',
  //     'react/no-did-update-set-state': 'warn',
  //     'react/no-direct-mutation-state': 'error',
  //     'react/no-find-dom-node': 'warn',
  //     'react/no-invalid-html-attribute': 'error',
  //     'react/no-is-mounted': 'warn',
  //     'react/no-namespace': 'error',
  //     'react/no-object-type-as-default-prop': 'warn',
  //     'react/no-redundant-should-component-update': 'warn',
  //     'react/no-render-return-value': 'warn',
  //     'react/no-string-refs': 'error',
  //     'react/no-this-in-sfc': 'error',
  //     'react/no-typos': 'warn',
  //     'react/no-unknown-property': ['error', { requireDataLowercase: true }],
  //     'react/no-unsafe': ['warn', { checkAliases: true }],
  //     'react/no-unstable-nested-components': ['error', { allowAsProps: false }],
  //     'react/no-unused-class-component-methods': 'warn',
  //     'react/no-unused-prop-types': 'warn',
  //     'react/no-unused-state': 'warn',
  //     'react/no-will-update-set-state': 'warn',
  //     'react/prefer-es6-class': ['error', 'always'],
  //     'react/prefer-exact-props': 'warn',
  //     'react/prefer-read-only-props': 'warn',
  //     'react/prefer-stateless-function': 'warn',
  //     'react/prop-types': 'error',
  //     'react/require-default-props': ['error', { forbidDefaultForRequired: true }],
  //     'react/require-render-return': 'error',
  //     'react/self-closing-comp': [
  //       'warn',
  //       {
  //         component: true,
  //         html: true,
  //       },
  //     ],
  //     'react/style-prop-object': 'error',
  //     'react/void-dom-elements-no-children': 'error',
  //   },
  // },
  // {
  //   files: ['src/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
  //   plugins: { 'react-hooks': reactHooks },
  //   rules: {
  //     'react-hooks/exhaustive-deps': 'error',
  //     'react-hooks/rules-of-hooks': 'error',

  //     'react-hooks/component-hook-factories': 'error',
  //     'react-hooks/config': 'error',
  //     'react-hooks/error-boundaries': 'warn',
  //     'react-hooks/gating': 'error',
  //     'react-hooks/globals': 'error',
  //     'react-hooks/immutability': 'error',
  //     'react-hooks/incompatible-library': 'warn',
  //     'react-hooks/preserve-manual-memoization': 'warn',
  //     'react-hooks/purity': 'error',
  //     'react-hooks/refs': 'error',
  //     'react-hooks/set-state-in-effect': 'warn',
  //     'react-hooks/set-state-in-render': 'warn',
  //     'react-hooks/static-components': 'error',
  //     'react-hooks/unsupported-syntax': 'warn',
  //     'react-hooks/use-memo': 'error',
  //   },
  // },

  {
    files: ['src/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    plugins: { '@eslint-react': eslintReact },
    rules: {
      '@eslint-react/error-boundaries': 'warn',
      '@eslint-react/exhaustive-deps': 'error',
      '@eslint-react/globals': 'error',
      '@eslint-react/immutability': 'error',
      '@eslint-react/no-access-state-in-setstate': 'warn',
      '@eslint-react/no-children-count': 'warn',
      '@eslint-react/no-children-for-each': 'warn',
      '@eslint-react/no-children-map': 'warn',
      '@eslint-react/no-children-only': 'warn',
      '@eslint-react/no-children-to-array': 'warn',
      '@eslint-react/no-class-component': 'warn',
      '@eslint-react/no-clone-element': 'error',
      '@eslint-react/no-component-will-mount': 'error',
      '@eslint-react/no-component-will-receive-props': 'error',
      '@eslint-react/no-component-will-update': 'error',
      '@eslint-react/no-context-provider': 'error',
      '@eslint-react/no-create-ref': 'warn',
      '@eslint-react/no-direct-mutation-state': 'error',
      '@eslint-react/no-duplicate-key': 'error',
      '@eslint-react/no-forward-ref': 'error',
      '@eslint-react/no-leaked-conditional-rendering': 'warn',
      '@eslint-react/no-missing-component-display-name': 'error',
      '@eslint-react/no-missing-key': 'warn',
      '@eslint-react/no-misused-capture-owner-stack': 'error',
      '@eslint-react/no-nested-component-definitions': 'error',
      '@eslint-react/no-nested-lazy-component-declarations': 'error',
      '@eslint-react/no-set-state-in-component-did-mount': 'warn',
      '@eslint-react/no-set-state-in-component-will-update': 'warn',
      '@eslint-react/no-unsafe-component-will-mount': 'warn',
      '@eslint-react/no-unsafe-component-will-receive-props': 'warn',
      '@eslint-react/no-unsafe-component-will-update': 'warn',
      '@eslint-react/no-unstable-context-value': 'warn',
      '@eslint-react/no-unstable-default-props': 'warn',
      '@eslint-react/no-unused-class-component-members': 'warn',
      '@eslint-react/no-unused-props': 'warn',
      '@eslint-react/no-unused-state': 'warn',
      '@eslint-react/no-use-context': 'error',
      '@eslint-react/purity': 'error',
      '@eslint-react/refs': 'error',
      '@eslint-react/rules-of-hooks': 'error',
      '@eslint-react/set-state-in-effect': 'warn',
      '@eslint-react/set-state-in-render': 'warn',
      '@eslint-react/static-components': 'error',
      '@eslint-react/unsupported-syntax': 'warn',
      '@eslint-react/use-memo': 'error',
      '@eslint-react/use-state': ['warn', { enforceSetterName: false }],

      '@eslint-react/jsx-no-children-prop': 'warn',
      '@eslint-react/jsx-no-children-prop-with-children': 'error',
      '@eslint-react/jsx-no-comment-textnodes': 'warn',
      '@eslint-react/jsx-no-key-after-spread': 'warn',
      '@eslint-react/jsx-no-namespace': 'error',
      '@eslint-react/jsx-no-useless-fragment': 'warn',

      '@eslint-react/rsc-function-definition': 'error',

      '@eslint-react/dom-no-dangerously-set-innerhtml': 'warn',
      '@eslint-react/dom-no-dangerously-set-innerhtml-with-children': 'warn',
      '@eslint-react/dom-no-find-dom-node': 'warn',
      '@eslint-react/dom-no-flush-sync': 'warn',
      '@eslint-react/dom-no-hydrate': 'error',
      '@eslint-react/dom-no-missing-button-type': 'warn',
      '@eslint-react/dom-no-missing-iframe-sandbox': 'warn',
      '@eslint-react/dom-no-render': 'error',
      '@eslint-react/dom-no-render-return-value': 'warn',
      '@eslint-react/dom-no-script-url': 'warn',
      '@eslint-react/dom-no-string-style-prop': 'error',
      '@eslint-react/dom-no-unknown-property': 'error',
      '@eslint-react/dom-no-unsafe-target-blank': 'warn',
      '@eslint-react/dom-no-use-form-state': 'error',
      '@eslint-react/dom-no-void-elements-with-children': 'error',

      '@eslint-react/web-api-no-leaked-event-listener': 'warn',
      '@eslint-react/web-api-no-leaked-fetch': 'warn',
      '@eslint-react/web-api-no-leaked-intersection-observer': 'warn',
      '@eslint-react/web-api-no-leaked-interval': 'warn',
      '@eslint-react/web-api-no-leaked-resize-observer': 'warn',
      '@eslint-react/web-api-no-leaked-timeout': 'warn',
    },
  },
  {
    files: ['src/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    plugins: { 'react-refresh': reactRefresh.plugin },
    rules: {
      'react-refresh/only-export-components': ['error', { checkJS: true }],
    },
  },
  {
    files: ['src/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    plugins: { 'jsx-a11y': jsxA11y },
    rules: {
      'jsx-a11y/alt-text': ['warn', { img: ['Image'] }],
      'jsx-a11y/anchor-has-content': 'error',
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-proptypes': 'error',
      'jsx-a11y/aria-role': 'error',
      'jsx-a11y/aria-unsupported-elements': 'error',
      'jsx-a11y/autocomplete-valid': 'error',
      'jsx-a11y/click-events-have-key-events': 'warn',
      'jsx-a11y/control-has-associated-label': 'warn',
      'jsx-a11y/heading-has-content': 'error',
      'jsx-a11y/html-has-lang': 'warn',
      'jsx-a11y/iframe-has-title': 'warn',
      'jsx-a11y/interactive-supports-focus': 'warn',
      'jsx-a11y/label-has-associated-control': 'warn',
      'jsx-a11y/lang': 'warn',
      'jsx-a11y/media-has-caption': 'warn',
      'jsx-a11y/mouse-events-have-key-events': 'warn',
      'jsx-a11y/no-access-key': 'error',
      'jsx-a11y/no-aria-hidden-on-focusable': 'error',
      'jsx-a11y/no-autofocus': 'error',
      'jsx-a11y/no-distracting-elements': 'error',
      'jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
      'jsx-a11y/no-noninteractive-element-interactions': 'error',
      'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
      'jsx-a11y/no-noninteractive-tabindex': 'error',
      'jsx-a11y/no-redundant-roles': 'warn',
      'jsx-a11y/no-static-element-interactions': 'error',
      'jsx-a11y/prefer-tag-over-role': 'warn',
      'jsx-a11y/role-has-required-aria-props': 'error',
      'jsx-a11y/role-supports-aria-props': 'error',
      'jsx-a11y/scope': 'error',
      'jsx-a11y/tabindex-no-positive': 'error',
    },
  },
  eslintConfigPrettier,

  {
    files: ['**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    plugins: { 'id-match': idMatch },
    rules: {
      'id-match/imports-match': ['warn', '^_?(?:(?:[A-Za-z][a-z]*|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/vars-match': ['warn', '^_?(?:(?:[A-Za-z][a-z]*|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/functions-match': ['warn', '^_?(?:(?:[A-Za-z][a-z]*|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/properties-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/classes-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/members-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/parameters-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/exports-match': ['warn', '^_?(?:(?:[A-Za-z][a-z]*|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
    },
  },
  {
    files: ['**/*.{ts,mts,cts,tsx}'],
    rules: {
      'id-match/interfaces-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/type-aliases-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/enumerations-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
    },
  },

  {
    files: ['**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
  },
]);
